### ISSUE TITLE
Scaling module assumes VirtualMachineInstanceReplicaSet values that aren't there

### ISSUE THREAD

**Issue by mmazur** [kubevirt/ansible-kubevirt-modules#116]
According to https://kubevirt.io/docs/workloads/controllers/virtual-machine-replica-set.html (last paragraph), a return object from a VMIRS invocation should contain "status/ready replicas" values. That's also how kubernetes' built–in RS does it.

The upstream k8s scaling code assumes __object.status.readyReplicas__ to exist as does our code ([here](https://github.com/kubevirt/ansible-kubevirt-modules/blob/master/lib/ansible/modules/clustering/kubevirt/kubevirt_scale_vmirs.py#L220)). Trouble is – VMIRS does not return that, so using scaling with __wait__ always fails with a timeout, since the code simply requires readyReplicas to be there.

I don't know what to do about this.

**Comment by pkliczewski** [comment]
> I don't know what to do about this.

Let's check what the code returns and fix our code so it can work with VMIRS.

**Comment by mmazur** [comment]
The issue is that our code is correct, it's just that VMIRS doesn't return the values required for our code to work. So I can't really fix it in our code.

What I'll do is prepare a simple test case for this and have all of you run it on your envs. If it works for you, then it's something with my env. If it doesn't, then we have an upstream bug and I'll fill a case with upstream.

**Comment by mmazur** [comment]
Martin suggested to just go upstream with this. I'll check it against latest dev env and write up my problem in an issue against kubevirt itself.

**Comment by pkliczewski** [comment]
@mmazur If you confirm that it doesn't work with latest master please open issue on KubeVirt and paste it here as reference.

**Comment by mmazur** [comment]
I've checked today with latest kubevirt and provider k8s-1.11.0 and emailed kubevirt-dev asking if anyone would like to clarify whether it's supposed to be this way.

**Comment by mmazur** [comment]
(Potential) discussion, for reference: https://groups.google.com/forum/#!topic/kubevirt-dev/WLoWkkvFgOE

**Comment by mmazur** [comment]
Roman helped me debug, it was an issue with my env.
