### ISSUE TITLE
copy past of kubevirt_vm in kubevirt_ovm

### ISSUE THREAD

**Issue by alexxa** [kubevirt/ansible-kubevirt-modules#12]
- kubevirt_ovm should use `ovm` variable, not `vm`.
- docstrings were not updated with ovm too. For example, Examples section lists `kubevirt_vm` module, not `kubevirt_ovm`.
 
And maybe in line 
https://github.com/kubevirt/ansible-kubevirt-modules/blob/master/library/kubevirt_ovm.py#L51
it should be s/virtualmachines/offlinevirtualmachines/?

**Comment by tripledes** [comment]
@alexxa let me know if #14 would be enough, though I still would like to refactor few things, e.g. linting, but in a separate issue and perhaps after merging #4.
