### ISSUE TITLE
e2e syntax error

### ISSUE THREAD

**Issue by mmazur** [kubevirt/ansible-kubevirt-modules#126]
e2e.yml has a bug in the VirtualMachine definition: it defines inline.spec.spec instead of inline.spec.template.spec (kubevirt_raw_vm.yml has this done correctly as far as I can tell). Please submit a PR with a fix before further extending that playbook. @vatsalparekh @adityaramteke

**Comment by adityaramteke** [comment]
@mmazur @pkliczewski I'm already fixing the same issue #124 here

**Comment by pkliczewski** [comment]
@adityaramteke I see that #124 was merged. Is this issue fixed?

**Comment by adityaramteke** [comment]
@adityaramteke Yes, this issue is resolved already.

**Comment by pkliczewski** [comment]
:+1:
