### ISSUE TITLE
Update docs for the New Era of Kubevirt Ansible Modules

### ISSUE THREAD

**Issue by mmazur** [kubevirt/ansible-kubevirt-modules#145]
Once all the new modules are in place (and old modules are dropped), the documentation should be updated in a single pass to make sure the new state of things is coherently explained.

**Comment by pkliczewski** [comment]
@mmazur I think we can work on this issue now.

**Comment by machacekondra** [comment]
What exactly do you mean by this issue? The documentation is part of Ansible:

 https://docs.ansible.com/ansible/devel/modules/list_of_cloud_modules.html#kubevirt

**Comment by pkliczewski** [comment]
This is the issue #145 :) I think we need to update documentation in this repo but if you feel there is nothing to be done please close

**Comment by mmazur** [comment]
Yes, I'd like our readme to be clearer on where you can find the stuff we do and what's where and how.

I will do the words. I do good words. Will be great.

**Comment by machacekondra** [comment]
Well if you think some kind of 'how to' use it, best practises etc. +1 from me.

**Comment by pkliczewski** [comment]
@mmazur Is this still valid issue? The modules were moved long time ago.

**Comment by mmazur** [comment]
Yup, still relevant. I'm planning on updating the docs to use the blog entries as the proper introduction… once those get published.

**Comment by mmazur** [comment]
Done.
