### ISSUE TITLE
Expose all k8s objects in kubevirt_vm's return json

### ISSUE THREAD

**Issue by mmazur** [kubevirt/ansible-kubevirt-modules#146]
According to docs (and in line with what upstream k8s modules do) `kubevirt_vm` should return info on both the VM and VMI it operates on. The latter is currently missing.

(Incidentally, once implemented, it might be a good idea to increase the number of `asserts` in `kubevirt_vm`'s unit tests to also cover VMI operation, since that status would now be available on module exit.)

**Comment by pkliczewski** [comment]
@mmazur Please give more information about what this issue is about. It is hard to understand from current description.

**Comment by pkliczewski** [comment]
@mmazur Is this still valid?

**Comment by mmazur** [comment]
My heart wants to say yes, but in reality this is waay too low prio to matter.
