### ISSUE TITLE
type: ClusterIP in k8s_service module gives a success result but does not create service

### ISSUE THREAD

**Issue by adityaramteke** [kubevirt/ansible-kubevirt-modules#153]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug
> /kind enhancement
 
/kind bug

**What happened**:
While creating a service with type `ClusterIP` using `k8s_service` module gives a success result but does not create any services

```bash

---
- name: Create a service
  hosts: localhost
  tasks:
    - name: create a service type of vm
      k8s_service:
        state: absent
        name: clusterip-service-test
        namespace: test-e2e
        type: ClusterIP
        ports:
          - name: clusterip
            port: 27016
            protocal: TCP
            targetPort: 22
        selector:
          kubevirt.io/vm: test-vm-cirros
        definition:
          metadata:
            labels:
              test: clusterip-test
```

**What you expected to happen**:
It should create service 

**How to reproduce it (as minimally and precisely as possible)**:
100%

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by mmazur** [comment]
Might that be because your playbook has `state: absent`? :)

**Comment by adityaramteke** [comment]
It works fine. Thanks
