### ISSUE TITLE
use kubevirt_vm instead of k8s

### ISSUE THREAD

**Issue by vatsalparekh** [kubevirt/ansible-kubevirt-modules#156]
This somehow slipped in, it should be `kubevirt_vm` instead of `k8s`
https://github.com/kubevirt/ansible-kubevirt-modules/blob/1a670bcc3bafac33e4a4dec7ff36de9080bce188/tests/playbooks/e2e.yaml#L43-L49

**Comment by pkliczewski** [comment]
I can see that e2e playbook was updated some time ago so closing this issue.
