### ISSUE TITLE
Bug: kubevirt modules return an admission webhook error instead of the proper 404: vm not found

### ISSUE THREAD

**Issue by mmazur** [kubevirt/ansible-kubevirt-modules#177]
Running our kubevirt_vm_status.yml playbook against kubevirt v0.12.0…v0.13.2 with non–existent vms, the result is:

```
    "msg": "Failed to create object: b'{\"kind\":\"Status\",\"apiVersion\":\"v1\",\"metadata\":{},\"status\":\"Failure\",\"message\":\"admission webhook \\\\\"virtualmachine-validator.kubevirt.io\\\\\" denied the request: spec.template.spec.domain in body is required\",\"reason\":\"Invalid\",\"details\":{\"causes\":[{\"message\":\"spec.template.spec.domain in body is required\"}]},\"code\":422}\\n'",
    "reason": "Unprocessable Entity",
    "status": 422
```

Question is – why.

/kind bug

**Comment by machacekondra** [comment]
What's your playbook?

**Comment by mmazur** [comment]
Ok, now I get it. Short version is that we're losing knowledge when using the k8s base classes. Our module can easily determine whether it wants to create a vm or just stop/start it. But that intention is never passed to the underlying code that actually executes on that (there's no way to pass that intention), which leaves said code guessing what we're trying to do. And if it guesses wrong, then instead of an error like "hey, you're trying to shut off a non–existent VM", we get insane error messages like "AAAAAAAAA critical webhook failure, this cluster will self destruct in 5 seconds AAAAAAA".

I'll add a todo item somewhere to take care of this.

**Comment by machacekondra** [comment]
But you don't know that. You don't know if user wanted actually create a stopped vm and forgot to pass some parameters. IMHO current behavior is correct and expected.

**Comment by mmazur** [comment]
Problem is that if we don't make that assumption about the user's intention, then we have issues with correctly handling error cases.

In the upstream bug David Vossel asked if there was a use-case for having a VMI without any devices. And the answer as far as I can tell is no, there isn't. Which means I'm free to interpret the lack of any device specification as a clear signal that a user just wants to alter the state. And I should probably do that, since that helps me out a lot.

I think the proper solution here is that if:
1. `state in ('running', 'stopped')` and
2. no other template definition has been provided (no devices, nothing; just `state`, `name`, `namespace`)
then the module should interpret it as issuing a PATCH on `spec.state` of an existing vm.

@pkliczewski what do you think?

(Btw: in which case we should probably also explicitly assume that if state==present and no template definition has been provided, then that's an error, since we don't support creating completely empty VMs.)

**Comment by machacekondra** [comment]
In that case you couldn't create VM in running state in one single module call? I think it's quite nice feature.

**Comment by machacekondra** [comment]
Ah, I forgot number 2). So in that case we would raise error that we can't change state of non-existent VM instead of raising an error what parameters forgot to pass. I still think current solution is better, but feel free to change.

**Comment by mmazur** [comment]
Fixed upstream.
