### ISSUE TITLE
options mismatch in docs section and main()

### ISSUE THREAD

**Issue by alexxa** [kubevirt/ansible-kubevirt-modules#18]
There are `disk` and `cdrom` options in docs section of [library/kubevirt_vm.py](https://github.com/kubevirt/ansible-kubevirt-modules/blob/master/library/kubevirt_vm.py) but they are not in main().

**Comment by karmab** [comment]
submitted https://github.com/kubevirt/ansible-kubevirt-modules/pull/19 to clean this up, along with pep8
