### ISSUE TITLE
Add parameter how to determine whether to update VMI or VM (when update available)

### ISSUE THREAD

**Issue by machacekondra** [kubevirt/ansible-kubevirt-modules#184]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug
> /kind enhancement

**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by mmazur** [comment]
Is there a discussion for this somewhere?

**Comment by pkliczewski** [comment]
@mmazur Here is good place to discuss it.

**Comment by machacekondra** [comment]
No, I just found today that it always update VM object, but user may want to update only VMI(like hotplug). So yes any ideas how to do it are welcome.

**Comment by mmazur** [comment]
Yesterday @masayag asked about adding devices to existing vms and was told that you can do it, but you need to do a restart for the changes to take effect (_Petr Kotas: You can add devices, But you have to restart the virtual machine to make the update_). In light of which I wonder why would this be needed? Or are there some kinds of vmi modifications that will be reflected in real–time, without the need for a restart?

**Comment by machacekondra** [comment]
Yes, for example memory or cpu hot plug, those are features supported for example by oVirt, so I believe those will be supported also by Kubevirt in future. You can also hot plug NIC and disk in oVirt.

**Comment by mmazur** [comment]
Ah, so something like `hotplug: bool` would be in order, which, if set to `true` (default: `false`, just to be safe?), would not only patch the VM, but also the VMI if that was already running. And then, depending on how much hotplug functionality is present in a given version of kubevirt, (some of) what has been patched in gets applied to the actual running vm.

I'm assuming here that:
1. When the template is patched, the VirtualMachine controller does not, on its own, update the VMI with that info.
2. Currently kubevirt_vm only patches the VM and leaves the VMI as it was.
