### ISSUE TITLE
Reconsider using Ansible path of parameters instead of JSON path in editable parameter of Kubevirt_template module

### ISSUE THREAD

**Issue by machacekondra** [kubevirt/ansible-kubevirt-modules#187]
`kubevirt_template` module contains `editable` field which contains of JSON path of KubeVirt API parameter, but user passes the Ansible flatten parameters, so it might be confusing for him what to actually pass. Improve `editable` parameter so it accept flatten structure.

**Comment by pkliczewski** [comment]
@machacekondra Do we still want to do it?

**Comment by machacekondra** [comment]
Yes, I would keep this open. It would be good improvement imho.
