### ISSUE TITLE
[UX] improve kubevirt_cdi_upload module

### ISSUE THREAD

**Issue by vatsalparekh** [kubevirt/ansible-kubevirt-modules#199]
**What happened**:
Current `kubevirt_cdi_upload` module expects to have a pvc where it can upload the image
**What you expected to happen**:
`virtctl image-upload` also aims to achieve similar flow from cli, but it creates a PVC and uploads to it directly. We can improve this module to avoid creating of pvc first and then uploading to it.

**Comment by pkliczewski** [comment]
What do you think if `pvc` is not available to create it and use `kubevirt_cdi_upload` as expected?

**Comment by mmazur** [comment]
Please rephrase the question.

**Comment by pkliczewski** [comment]
@mmazur is it still valid?

**Comment by mmazur** [comment]
Not in its current form. Integrating upload functionality into `kubevirt_pvc` and `kubevirt_vm` is still on the table, but that's not what this issue is about. Closing.
