### ISSUE TITLE
pvc and registrydisk design

### ISSUE THREAD

**Issue by alexxa** [kubevirt/ansible-kubevirt-modules#23]
Review usage of pvc and registrydisk options on all modules, please. Whether any should be required and have a default value. ATM docs say none is required, but if none is specified, an error `Missing disk information` pops up.

**Comment by fabiand** [comment]
Please do not add support for registryDisks to the ansible modules yet.

We need to clarfiy this approach a little more before we want to publcily support it.

**Comment by tripledes** [comment]
@fabiand should we just use `pvc` then ?

**Comment by fabiand** [comment]
yes please

**Comment by karmab** [comment]
@fabiand the thing is that the registry disk is already there, so should we drop from the code ?

**Comment by fabiand** [comment]
No, let's just not expose it in the ansible modules.

**Comment by tripledes** [comment]
@alexxa @fabiand just pushed #35 to hide `registrydisk` and made `pvc` required. Also amended some test playbooks to use `pvc` as well. Once the future of `registrydisk` is clear, it can be easily re-enabled.
