### ISSUE TITLE
Repeated CI instability on minikube (travis)

### ISSUE THREAD

**Issue by mmazur** [kubevirt/ansible-kubevirt-modules#240]
/kind bug

We've been hitting a random issue when running our ~~pvc creation~~ tests, which ends up with this error message:

```
Failed to create object: b'{\"kind\":\"Status\",\"apiVersion\":\"v1\",\"metadata\":{},\"status\":\"Failure\",\"message\":\"Internal error occurred: resource quota evaluates timeout\",\"reason\":\"InternalError\",\"details\":{\"causes\":[{\"message\":\"resource quota evaluates timeout\"}]},\"code\":500}\\n'"
```

Since it wasn't consistent, we've chalked it up to TravisCI being weird. Now we're on Jenkins with completely different hw running the cluster+tests and are seeing the same issue.

Google says that this is rare, but does happen on occasion:

1. https://github.com/gluster/gluster-csi-driver/issues/92
2. https://github.com/kubernetes/kubernetes/issues/67531 

Two scenarios come to my mind at this time:

1. K8S has performance knobs that can be tuned and the https://github.com/kubevirt/kubevirtci cluster we're using has them turned down too much and we're on occasion getting some parts of the cluster (etcd?) to choke on the workload.
    - [ ] Possible action: ask kubevirtci people about their take on this
2. This is simply an obscure bug and we're unlucky.
    - [x] ~~Action1: mess around with task ordering in our test playbooks to maybe help avoid hitting the issue.~~ Tried, didn't help, it just happens on a different task now. (See comments.)
    - [ ] Action2: get our jenkins mock-runner to endlessly loop the tests on my own hw and hope to hit the bug, at which point I can get debug info out of it.
    - [ ] Action3: connect with our CI people and get them to somehow freeze a CI machine for further debugging next time we hit the issue.

Suggestions welcome.

**Comment by mmazur** [comment]
Btw, the timeout on this is only 10 seconds: https://github.com/kubernetes/kubernetes/blob/cc67ccfd7f4f0bc96d7f1c8e5fe8577821757d03/plugin/pkg/admission/resourcequota/controller.go#L620

**Comment by pkliczewski** [comment]
@mmazur can you check how kubevirt ci is working? I think they should have solved the issues already. Let's reuse what they did so far.

**Comment by mmazur** [comment]
@davidvossel has started working on a consumable version of the cluster setup/teardown scripts just now. As soon as they're ready, we'll switch. If it fixes this issue, great. If not, then it won't be just our problem. :)

**Comment by mmazur** [comment]
Just occurred to me that travis was minikube and jenkins is kubevirtci, so it must be a weird bug we're hitting.

**Comment by mmazur** [comment]
Seems that ever since [`kubevirt_pvc` tests were moved to run first](https://github.com/kubevirt/ansible-kubevirt-modules/commit/bfb491314efd16c1d9e811c80466a9d2181a14e5#diff-d244dcc82dba8ee1c894c4b4071a2798) the same issue gets hit on a different playbook. [This build log](https://api.travis-ci.org/v3/job/550205866/log.txt) hits the same issue in the preset playbook, which is also near the end of the tests, as `kubevirt_pvc.yml` used to be.

This would suggest we are occasionally hitting some kind of bug when we overburden the cluster with all of our testing.

It's unfortunate I didn't start documenting this earlier, as I'm not sure now whether this is Travis–only or whether we've seen this on Jenkins as well. I'll go with Travis–only until I get a same log from Jenkins.

**Comment by mmazur** [comment]
Yup, the fails happen close to the end of the ansible run, but not always at the same point:
-  [`kubevirt_preset`](https://api.travis-ci.org/v3/job/550302839/log.txt)
- [`e2e`](https://api.travis-ci.org/v3/job/550302838/log.txt)

**Comment by mmazur** [comment]
Just checked and minikube does not set any memory limits on the containers (except the coredns ones), so with 7+ gigs at its disposal, the cluster is probably not running out of memory.

**Comment by mmazur** [comment]
```
NAMESPACE     NAME                               READY   STATUS             RESTARTS   AGE
cdi           cdi-apiserver-599d6fd49-kdzzb      1/1     Running            0          11m
cdi           cdi-deployment-5d4764ff96-gvsx5    0/1     CrashLoopBackOff   4          11m
cdi           cdi-operator-7cd554798c-xpx7k      0/1     CrashLoopBackOff   4          12m
cdi           cdi-uploadproxy-5c57b4db65-mwnxn   1/1     Running            0          11m
kube-system   coredns-fb8b8dccf-pg527            1/1     Running            0          13m
kube-system   coredns-fb8b8dccf-qx6r2            1/1     Running            0          13m
kube-system   etcd-minikube                      1/1     Running            0          12m
kube-system   kube-addon-manager-minikube        1/1     Running            0          12m
kube-system   kube-apiserver-minikube            1/1     Running            0          12m
kube-system   kube-controller-manager-minikube   0/1     CrashLoopBackOff   5          12m
kube-system   kube-proxy-bkmx6                   1/1     Running            0          13m
kube-system   kube-scheduler-minikube            0/1     CrashLoopBackOff   5          12m
kube-system   storage-provisioner                1/1     Running            0          13m
kubevirt      virt-api-854b6cbbb8-95hn6          1/1     Running            0          11m
kubevirt      virt-api-854b6cbbb8-nqvpz          1/1     Running            1          11m
kubevirt      virt-controller-546799f76-5jqwk    1/1     Running            2          11m
kubevirt      virt-controller-546799f76-t5k8d    0/1     CrashLoopBackOff   2          11m
kubevirt      virt-handler-fxfgc                 1/1     Running            0          11m
kubevirt      virt-operator-9646fdf49-5z7z2      0/1     CrashLoopBackOff   3          12m
kubevirt      virt-operator-9646fdf49-78wtb      1/1     Running            2          12m
```

Source: https://api.travis-ci.org/v3/job/550713626/log.txt

**Comment by mmazur** [comment]
Added a workaround for this to our tests that kick in when we're running on travis ([here](https://github.com/kubevirt/ansible-kubevirt-modules/pull/262/commits/a62f135c6da65d57c58e931eea6b58f09ac23b2b)). Basically a bunch of sleeps to let the cluster recover from errors between playbooks.

**Comment by pkliczewski** [comment]
@mmazur Is it something we still want to work on?

**Comment by mmazur** [comment]
Yes, very much so. Next time I'm working on something in the vicinity, I'll definitively try to get this debugged, as we rely on the travis CI very heavily and it'd be great if that didn't fail every once in a while for no good reason.
