### ISSUE TITLE
ansible @devel and @stable-2.8 break kubevirt_pvc (annotations aren't set)

### ISSUE THREAD

**Issue by mmazur** [kubevirt/ansible-kubevirt-modules#242]
You know how CI has been flaky recently?

One reason is that #240 is actually a real thing that we're hitting on occasion. (But that's a different story.)

The other is that CI is using devel branch of ansible (on purpose, to catch stuff early) and that actually broke in recent days. And that's the other bug we've been hitting.

Specifics are: if trying to utilize CDI with `kubevirt_pvc`, that depends on setting annotations on the PVC. But with most recent devel ansible, annotations aren't set, so the whole thing times out.

This warrants an investigation on Monday. I'll also push a PR against our tests to increase verbosity, so that this becomes easier to notice next time.

/kind bug

**Comment by pkliczewski** [comment]
Tracked by BZ [1716905](https://bugzilla.redhat.com/1716905)

**Comment by mmazur** [comment]
Github logic was mistaken.

**Comment by mmazur** [comment]
Fix merged both in stable-2.8 and devel branches. 2.8.2 should be released in a few days. Closing.
