### ISSUE TITLE
Further CI goals

### ISSUE THREAD

**Issue by mmazur** [kubevirt/ansible-kubevirt-modules#246]
We use Travis and Jenkins. Based on their inherent limitations and the past few weeks of experience:

1. Travis is quicker/more reliable to respond than Jenkins.
2. But Travis can only run minikube with emulated VMIs.
3. While Jenkins can run anything kubevirt/kubevirtci supports, including (eventually) okd4.
4. Travis has the ability to run manual builds with env overrides (for e.g. testing upstream ansible PRs), while Jenkins does not.

Proposed goals:

1. **Add .z streams to testing matrix.**
5. Conditional test skipping based on open github issues.
2. Re-enable travis to run minikube, the universal tests and separately devel and stable ansible (in a travis "matrix" cfg).
    - Ideally with a good way to bring back the test–ansible–PR features, as that would be really useful.
4. Switch to using kubevirt/kubevirtci for cluster up/cluster down scripting.
    - Once OKD4 becomes an option, move Jenkins to running that and testing all of it: stable and devel ansible with universal and openshift tests against okd4.
1. Make sure our tests (playbooks) are always split into universal and openshift–specific ones (this is already sort of the case, just not explicit).

/kind enhancement

**Comment by pkliczewski** [comment]
I would add one more which in my opinion is the most important:
5. Make the CI reliable

We can't afford CI to always fail

**Comment by mmazur** [comment]
The CI is reliable. It reliably tells you that all of our playbooks are fine with ansible 2.8, but they fail on the pvc module with ansible 2.9. :) But you need to actually go through the logs to figure that out.

What we need is a way to quickly figure out where the tests fails, to be able to make debug/ignore/merge decisions. Which is why I've written this down, so that I have a basis for a story proposal for next sprint.

**Comment by pkliczewski** [comment]
We notice that the tests fail by seeing CI red. Now we see it red all the time and it is not acceptable. This needs to be the highest priority.

**Comment by mmazur** [comment]
Done, done and done. Closing.
