### ISSUE TITLE
KubeVirt on Mac can't find support code for module

### ISSUE THREAD

**Issue by B3DTech** [kubevirt/ansible-kubevirt-modules#281]
/kind bug

**What happened**:
Installed Ansible on Mac for the user using pip method.

Built a KubeVirt playbook and ran it with ansible-playbook deployvm.yaml and get the following error:

`fatal: [localhost]: FAILED! => {"msg": "Could not find imported module support code for ansible_collections.community.kubevirt.plugins.modules.kubevirt_vm.  Looked for (['ansible_collections.community.kubernetes.plugins.module_utils.common.AUTH_ARG_SPEC', 'ansible_collections.community.kubernetes.plugins.module_utils.common'])"}`

**What you expected to happen**:

Dependencies are find

**How to reproduce it (as minimally and precisely as possible)**:
OS X 12.3

5314  pip
5315  python -m pip install --user ansible
5320  ansible-playbook server2022.yaml

The playbook looks like:

`---
- name: Create Windows 2022 VM
  hosts: localhost
  connection: local
  tasks:
    - name: Create Windows 2022 VirtVM
      kubevirt_vm:
        namespace: default
        name: win2022
        state: running
        cpu_cores: 2
        memory: 4Gi
        disks:
          - name: containerdisk
            volume:
              containerDisk:
                image: mcr.microsoft.com/windows/server:ltsc2022
              disk:
                bus: virtio`

**Environment**:
- KubeVirt version (use `virtctl version`):  0.50.0
- Kubernetes version (use `kubectl version`): 1.23.2
- VM or VMI specifications:
- Cloud provider or hardware configuration:  Rancher K8S cluster
- OS (e.g. from /etc/os-release):  OS x
- Kernel (e.g. `uname -a`): Darwin MaxBookPro.local 21.4.0 Darwin Kernel Version 21.4.0: Tue Jan 18 13:02:01 PST 2022; root:xnu-8020.100.406.0.1~18/RELEASE_X86_64 x86_64

**Comment by mmazur** [comment]
I believe since the modules have been upstreamed, somewhere upstream should be the place to file a bug. This repo should likely be archived.

**Comment by pkliczewski** [comment]
@fabiand FYI
