### ISSUE TITLE
add kubevirt module utility

### ISSUE THREAD

**Issue by alexxa** [kubevirt/ansible-kubevirt-modules#31]
Many [Ansible modules have utilities](http://docs.ansible.com/ansible/latest/dev_guide/developing_modules.html#appendix-module-utilities) which contain various functions used in modules. I think KubeVirt can have the same, so there will be no duplicated functions across library/kubevirt_*.py

**Comment by tripledes** [comment]
Closing this issue, with the rewrite, module utilities are in place.
