### ISSUE TITLE
add integration tests

### ISSUE THREAD

**Issue by alexxa** [kubevirt/ansible-kubevirt-modules#42]

**Comment by vatsalparekh** [comment]
@alexxa can you describe which tests you meant?
We now have e2e and other test playbooks working.

**Comment by pkliczewski** [comment]
@alexxa Please check whether e2e is is OK for you.

**Comment by alexxa** [comment]
I'm not on this project anymore. Please check with @nellyc if she is happy with the current TP and tests.

IMO, beside e2e tests on modules functionality, a module needs to pass the certain Ansible tests. See [1]. For example, that module's documentation is all build correctly, etc.

[1] https://docs.ansible.com/ansible/2.7/dev_guide/testing.html

**Comment by pkliczewski** [comment]
@alexxa Sound interesting. Let's see whether we could start using `ansible-test`. @adityaramteke @vatsalparekh  what do you think?

**Comment by alexxa** [comment]
@pkliczewski Mind that some sanity tests tools for Ansible may be outdated already. There were some, when I looked at them last time. Nevertheless, investigating testing of Ansible modules helped me to catch BZes on the module documentation, and others. The whole point beside my comment, is that this module should fully follow Ansible modules development policies.

**Comment by alexxa** [comment]
@pkliczewski ansible testing tooling also checks dev practices =) Feel free to rename this issue, or open a new one.

**Comment by adityaramteke** [comment]
@pkliczewski sound interesting. I had already discussed with @nellyc regarding how we are going to test the ansible module and we can definitely try `ansible-test`

**Comment by pkliczewski** [comment]
@adityaramteke Great, I am assigning this issue to you.

**Comment by vatsalparekh** [comment]
Closing this as we have e2e.yaml merged, and modules are run in CI now
