### ISSUE TITLE
shared documentation fragments

### ISSUE THREAD

**Issue by alexxa** [kubevirt/ansible-kubevirt-modules#48]
If there is any duplication in modules documentation, [documentation fragments](https://ansible-manual.readthedocs.io/en/stable-2.3/dev_guide/developing_modules_documenting.html#documentation-fragments) should be used.

**Comment by tripledes** [comment]
Thanks @alexxa, I think it could be part of #47

**Comment by tripledes** [comment]
@alexxa been working on this issue (see #69) but so far I cannot find a way to test the fragments as the module doesn't live in ansible tree.

The only way I managed ansible-doc to find the fragments was to link (ln -s) to $ANSIBLE_HOME/lib/ansible/utils/module_docs_fragments/$file.py.

I've just open an issue for Ansible https://github.com/ansible/ansible/issues/42938 , I might be missing something though but I cannot find any documentation or example telling what configuration setting or environment variable to set for `ansible-doc` being able to find our fragments.

I see to options here:

* Merge #69 anyway and if/when we send the PR to Ansible, that will be done already and will work, but until we do this, `ansible-doc` won't work for us or for any potential user.
* Duplicate module documentation in the actual modules until we submit the PR to Ansible.

What do you think? I'd go for documenting each module individually, even if, for now, that means duplicating documentation.

**Comment by tripledes** [comment]
@alexxa I'm labeling this one as blocked. Feel free to close it, can be reopen eventually.

**Comment by tripledes** [comment]
Got a reply on the ansible issue, it's been considered a feature request as it was never intended to work the way we need to work. So our only option is to wait for it to get implemented or write the fragments whenever we are ready to send a PR for the modules be added to ansible-core. Whatever comes first.
