### ISSUE TITLE
Some actions raise an exception

### ISSUE THREAD

**Issue by tripledes** [kubevirt/ansible-kubevirt-modules#60]
Due to https://github.com/kubevirt/client-python/issues/21 some actions like removing a VirtualMachineInstance or getting its facts are raising an exception complaining about missing data model `V1InterfaceBridge`.

**Comment by pkliczewski** [comment]
We merged this workaround https://github.com/kubevirt/kubevirt/pull/1452 and the problem does not occur any more. Real fix is in progress here: https://github.com/kubevirt/kubevirt/pull/1457
