### ISSUE TITLE
Move modules using patch() to KubeVirt Python client

### ISSUE THREAD

**Issue by tripledes** [kubevirt/ansible-kubevirt-modules#61]
Now that https://github.com/kubevirt/client-python/issues/20 seems to be fixed, `kubevirt_scale_vmirs` and `kubevirt_vm_status` should use KubeVirt's Python client and avoid Kubernetes when possible.

**Comment by tripledes** [comment]
Blocked by https://github.com/kubevirt/client-python/issues/24

**Comment by vatsalparekh** [comment]
@mmazur @machacekondra @pkliczewski now that we moved to dynamic client, is this issue valid anymore?

**Comment by machacekondra** [comment]
It's not. IMHO can be closed.
