### ISSUE TITLE
Support multiple KubeVirt API versions

### ISSUE THREAD

**Issue by tripledes** [kubevirt/ansible-kubevirt-modules#77]
Currently, KubeVirt's API is still at pre-v1 therefore the Python client doesn't support anything else.

The modules reference `V1*` objects everywhere, but eventually other versions will have to be supported as well.

Ideally, [this RFE](https://github.com/kubevirt/client-python/issues/19) would be implemented and it'll hide the Python client implementation details, easing the modules code. If that RFE doesn't get implemented some abstraction will be needed in the modules to handle different API versions.

**Comment by vatsalparekh** [comment]
@mmazur @machacekondra now with the dynamic client, is this still relevant?

**Comment by mmazur** [comment]
This can be closed, the current code does not statically use any particular api version.

**Comment by machacekondra** [comment]
Well, kind of. We do hardcode 'kubevirt.io/v1alpha2' as for now. I actually think we should keep this open, and think of support of different API versions.

**Comment by pkliczewski** [comment]
Now with the recent change in api version the modules are not working due to hardcoded [version](https://github.com/kubevirt/ansible-kubevirt-modules/blob/master/lib/ansible/module_utils/kubevirt.py#L15). We need to implement detection mechanism as in https://github.com/fog/fog-kubevirt/pull/64
